return {
  'abeldekat/lazyflex.nvim',
  enabled = false,
  import = 'lazyflex.hook',

  -- opts = { enable_match = false, kw = { "nvim-treesitter" } },
  opts = {
    kw = {
      -- cmp
      'plenary.nvim',
      'nvim-cmp',
      'cmp-nvim-lsp',
      'cmp-buffer',
      'cmp-path',
      'cmp-cmdline',
      'codeium.nvim',
      'LuaSnip',
      'cmp_luasnip',
      -- cmp
      'plenary.nvim',
      'nvim-web-devicons',
      'im-arpeggio',
      'vim-abolish',
      'YankAssassin.vim',
      'flatten.nvim',
      'nvim-colorizer.lua',
      'numb.nvim',
      'nvim-treesitter-textobjects',
      'nvim-ts-autotag',
      'vim-exchange',
      'mkdir.nvim',
      'tree-setter',
      'project.nvim',
      'virt-column.nvim',
      -- 'vim-textobj-user',
      -- 'vim-textobj-comment',
      -- 'vim-textobj-line',
      -- 'vim-textobj-entire',
      -- 'vim-textobj-chainmember',
      'nvim-autopairs',
      'local-highlight.nvim',
      'splitjoin.nvim',
      'live-command.nvim',
      'mini.ai',
      'vim-surround-funk',
      'highlight-undo',
      'conform.nvim',
      'sideway.vim',
      'vim-highlightedyank',
      'mini.indentscope',
      'gitsigns.nvim',
      'vim-auto-save',
      'mini.align',
      'hydra.nvim',
      'lualine.nvim',
      'flash.nvim',
      'sniprun',
      'checker.nvim',
      'nvim-surround',
      'vim-asterisk',
      'nvim-treesitter',
      -- 'vim-matchup',
      'vim-search-pulse',
      'midnight.nvim',
      'codeium.nvim',
      'dial.nvim',
      'putter.nvim',
      'Comment.nvim',
      'nvim-code-action-menu',
      'bufferline.nvim',
      'nvim-spider',
      'appender.nvim',
      'printer.nvim',
      'nvim-various-textobjs',
      'stay-in-place.nvim',
      'nvim-lightbulb',
      'nvim-lspconfig',
    },
  },
}
